Repository lugnitdgp/Chatopia_GSOC_Heat_24, pull requests merged in 2024-10, with the labels that each got.

#13 Update README.md
  README.md
Labels: good first issue

#23 Added Forward message feature
  chatopia/app/api/conversations/route.ts
  chatopia/app/api/messages/route.ts
  chatopia/app/components/inputs/Select.tsx
  chatopia/app/conversations/[conversationId]/components/Form.tsx
  chatopia/app/conversations/[conversationId]/components/ForwardModal.tsx
  chatopia/app/conversations/[conversationId]/components/MessageBox.module.css
  chatopia/app/conversations/[conversationId]/components/MessageBox.tsx
  chatopia/app/conversations/components/ConversationBox.tsx
  chatopia/app/conversations/components/ConversationList.tsx
  chatopia/app/conversations/components/GroupChatModal.tsx
  chatopia/prisma/schema.prisma
Labels: Intermediate, Hacktoberfest-accepted

#28 Display targeted error messages for invalid inputs during the user register process
  chatopia/app/(site)/components/AuthForm.module.css
  chatopia/app/(site)/components/AuthForm.tsx
  chatopia/app/api/register/route.ts
Labels: Intermediate, Hacktoberfest-accepted

#31 Update layout.tsx
  chatopia/app/layout.tsx
Labels: Hacktoberfest-accepted
